/**
 * O cardápio de exemplo que uma loja NOVA recebe no dia em que é criada.
 *
 * Morava em `src/data/` como se fosse dado do front, mas só o servidor lê isto
 * — e a partir do multi-tenant ele é literalmente o template de onboarding: a
 * rota que cria uma loja copia estes produtos para dentro dela.
 */
import type { ExtraOption, Product } from '../../../../contract/catalog/types';
const CALDINHO_FLAVORS = [
  'Caldinho de Feijão Preto',
  'Caldinho de Camarão',
  'Caldinho de Mocotó',
  'Caldinho de Sururu',
  'Caldinho de Vaca Atolada',
  'Caldinho Verde de Mandioca',
];

const BEER_OPTIONS = ['Heineken 600ml', 'Amstel 600ml', 'Spaten 600ml'];

export const COMBO_SLOTS_HAPPY_HOUR = [
  {
    id: 'slot-caldinho-1',
    label: '1º Caldinho (escolha o sabor)',
    required: true,
    options: CALDINHO_FLAVORS.map((label, i) => ({ id: `opt-c1-${i}`, label })),
  },
  {
    id: 'slot-caldinho-2',
    label: '2º Caldinho (escolha o sabor)',
    required: true,
    options: CALDINHO_FLAVORS.map((label, i) => ({ id: `opt-c2-${i}`, label })),
  },
  {
    id: 'slot-cerveja-1',
    label: '1ª Cerveja (escolha a marca)',
    required: true,
    options: BEER_OPTIONS.map((label, i) => ({ id: `opt-b1-${i}`, label })),
  },
  {
    id: 'slot-cerveja-2',
    label: '2ª Cerveja (escolha a marca)',
    required: true,
    options: BEER_OPTIONS.map((label, i) => ({ id: `opt-b2-${i}`, label })),
  },
];

export const COMBO_SLOTS_CASAL = [
  {
    id: 'slot-caldinho-2x',
    label: 'Escolha 2 Caldinhos (sabores podem repetir ou variar)',
    required: true,
    minChoices: 2,
    maxChoices: 2,
    options: CALDINHO_FLAVORS.map((label, i) => ({ id: `opt-c1-${i}`, label })),
  },
  {
    id: 'slot-petisco',
    label: 'Petisco (escolha a opção)',
    required: true,
    options: [
      { id: 'opt-p-0', label: 'Batata Frita da Casa' },
      { id: 'opt-p-1', label: 'Carne de Sol Acebolada com Macaxeira' },
    ],
  },
];

export const COMBO_SLOTS_FAMILIA = [
  {
    id: 'slot-caldinho-3x',
    label: 'Escolha 3 Caldinhos (sabores podem repetir ou variar)',
    required: true,
    minChoices: 3,
    maxChoices: 3,
    options: CALDINHO_FLAVORS.map((label, i) => ({ id: `opt-c3-${i}`, label })),
  },
  {
    id: 'slot-petisco-f',
    label: 'Petisco Grande (escolha a opção)',
    required: true,
    options: [
      { id: 'opt-pf-0', label: 'Batata Frita da Casa' },
      { id: 'opt-pf-1', label: 'Carne de Sol Acebolada com Macaxeira' },
      { id: 'opt-pf-2', label: 'Calabresa Acebolada com Queijo Coalho' },
    ],
  },
  {
    id: 'slot-bebidas-2x',
    label: 'Escolha 2 Bebidas',
    required: true,
    minChoices: 2,
    maxChoices: 2,
    options: BEER_OPTIONS.map((label, i) => ({ id: `opt-bf-${i}`, label })),
  },
];

export const COMMON_EXTRAS: ExtraOption[] = [
  { id: 'ext-1', name: 'Queijo Coalho em Cubos', price: 3.50 },
  { id: 'ext-2', name: 'Bacon Crocante em Cubinhos', price: 4.00 },
  { id: 'ext-3', name: 'Torresmo de Rolo Pururucado', price: 4.50 },
  { id: 'ext-4', name: 'Ovo de Codorna (3 un)', price: 2.50 },
  { id: 'ext-5', name: 'Cheiro Verde & Coentro Extra', price: 1.50 },
  { id: 'ext-6', name: 'Torradinhas Temperadas da Casa', price: 3.00 },
  { id: 'ext-7', name: 'Molho de Pimenta Baiana Caseiro', price: 2.00 },
];

export const INITIAL_PRODUCTS: Product[] = [
  // CALDINHOS
  {
    id: 'cal-1',
    name: 'Caldinho de Feijão Preto Tradicional',
    description: 'Aveludado caldinho de feijão preto com paio, bacon, charque desfiado e cheiro verde fresco. Acompanha torradinhas da casa.',
    category: 'caldinhos',
    basePrice: 18.90,
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&q=80&w=800',
    isPopular: true,
    available: true,
    rating: 0,
    reviewsCount: 0,
    prepTimeMinutes: 12,
    allowedExtras: COMMON_EXTRAS,
    hasSizeOption: true,
  },
  {
    id: 'cal-2',
    name: 'Caldinho de Camarão',
    description: 'Caldo de camarão com leite de coco, azeite de dendê e camarões inteiros salteados no alho.',
    category: 'caldinhos',
    basePrice: 24.90,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&q=80&w=800',
    isPopular: true,
    available: true,
    rating: 0,
    reviewsCount: 0,
    prepTimeMinutes: 15,
    allowedExtras: COMMON_EXTRAS,
    hasSizeOption: true,
  },
  {
    id: 'cal-3',
    name: 'Caldinho de Mocotó',
    description: 'Mocotó bovino com legumes, ovos de codorna e torresmo.',
    category: 'caldinhos',
    basePrice: 16.90,
    originalPrice: 21.90,
    image: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&q=80&w=800',
    isFeatured: true,
    isFlashPromo: true,
    available: true,
    rating: 0,
    reviewsCount: 0,
    prepTimeMinutes: 10,
    allowedExtras: COMMON_EXTRAS,
    hasSizeOption: true,
  },
  {
    id: 'cal-4',
    name: 'Caldinho de Sururu do Litoral',
    description: 'Sururu fresco refogado com leite de coco, coentro e pimentão.',
    category: 'caldinhos',
    basePrice: 22.90,
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&q=80&w=800',
    available: true,
    rating: 0,
    reviewsCount: 0,
    prepTimeMinutes: 15,
    allowedExtras: COMMON_EXTRAS,
    hasSizeOption: true,
  },
  {
    id: 'cal-5',
    name: 'Caldinho de Vaca Atolada',
    description: 'Costela bovina cozida lentamente até desmanchar, reduzida num creme consistente de mandioca com manteiga de garrafa.',
    category: 'caldinhos',
    basePrice: 20.90,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=800',
    isPopular: true,
    available: true,
    rating: 0,
    reviewsCount: 0,
    prepTimeMinutes: 12,
    allowedExtras: COMMON_EXTRAS,
    hasSizeOption: true,
  },
  {
    id: 'cal-6',
    name: 'Caldinho Verde de Mandioca com Bacon',
    description: 'Creme leve de mandioca com couve fatiada fininha, calabresa defumada em rodelas e cubos de bacon bem dourados.',
    category: 'caldinhos',
    basePrice: 17.90,
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&q=80&w=800',
    available: true,
    rating: 0,
    reviewsCount: 0,
    prepTimeMinutes: 10,
    allowedExtras: COMMON_EXTRAS,
    hasSizeOption: true,
  },

  // PETISCOS
  {
    id: 'pet-1',
    name: 'Batata Frita da Casa',
    description: 'Porção reforçada de batatas palito crocantes cobertas com cheddar derretido, bacon frito e farofa de torresmo.',
    category: 'petiscos',
    basePrice: 32.90,
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&q=80&w=800',
    isPopular: true,
    available: true,
    rating: 0,
    reviewsCount: 0,
    prepTimeMinutes: 20,
  },
  {
    id: 'pet-2',
    name: 'Carne de Sol Acebolada com Macaxeira',
    description: 'Carne de sol artesanal salteada na manteiga de garrafa com rodelas de cebola roxa e macaxeira frita bem macia e douradinha.',
    category: 'petiscos',
    basePrice: 54.90,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=800',
    isPopular: true,
    available: true,
    rating: 0,
    reviewsCount: 0,
    prepTimeMinutes: 25,
  },
  {
    id: 'pet-3',
    name: 'Frango a Passarinho Crocante',
    description: '1kg de pedacinhos de frango temperados no alho frito, ervas finas e limão taiti, servidos com molho tártaro especial.',
    category: 'petiscos',
    basePrice: 39.90,
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&q=80&w=800',
    available: true,
    rating: 0,
    reviewsCount: 0,
    prepTimeMinutes: 22,
  },
  {
    id: 'pet-4',
    name: 'Torresmo de Rolo Pururucado',
    description: 'Tiras de pancetta enrolada pururucada com a pele estalando, acompanhada de geleia de pimenta da casa e fatias de limão.',
    category: 'petiscos',
    basePrice: 28.90,
    originalPrice: 34.90,
    isFlashPromo: true,
    image: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&q=80&w=800',
    available: true,
    rating: 0,
    reviewsCount: 0,
    prepTimeMinutes: 15,
  },
  {
    id: 'pet-5',
    name: 'Arrumadinho de Charque Pernambucano',
    description: 'Combinação clássica: feijão macassar temperado, farofa crocante de manteiga, vinagrete bem fresco e charque frito acebolado.',
    category: 'petiscos',
    basePrice: 42.90,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80&w=800',
    available: true,
    rating: 0,
    reviewsCount: 0,
    prepTimeMinutes: 20,
  },

  // BEBIDAS
  {
    id: 'beb-1',
    name: 'Cerveja 600ml',
    description: 'Escolha no pedido entre Heineken, Amstel ou Spaten. Entregue em embalagem térmica, gelada.',
    category: 'bebidas',
    basePrice: 14.90,
    image: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&q=80&w=800',
    isPopular: true,
    available: true,
    rating: 0,
    reviewsCount: 0,
    prepTimeMinutes: 3,
  },
  {
    id: 'beb-2',
    name: 'Refrigerante Lata (350ml)',
    description: 'Coca-Cola Zero, Coca Tradicional, Guaraná Antarctica ou Sprite gelados.',
    category: 'bebidas',
    basePrice: 6.50,
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=800',
    available: true,
    rating: 0,
    reviewsCount: 0,
    prepTimeMinutes: 2,
  },
  {
    id: 'beb-3',
    name: 'Suco Natural de Cajá / Graviola (500ml)',
    description: 'Suco da polpa natural da fruta regional, batido na hora com gelo. Opção com ou sem açúcar.',
    category: 'bebidas',
    basePrice: 9.90,
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&q=80&w=800',
    available: true,
    rating: 0,
    reviewsCount: 0,
    prepTimeMinutes: 5,
  },
  {
    id: 'beb-4',
    name: 'Água de Coco Geladinha (500ml)',
    description: 'Água de coco natural, engarrafada no dia.',
    category: 'bebidas',
    basePrice: 7.90,
    image: 'https://images.unsplash.com/photo-1525385133512-2f3bdd039054?auto=format&fit=crop&q=80&w=800',
    available: true,
    rating: 0,
    reviewsCount: 0,
    prepTimeMinutes: 2,
  },

  // COMBOS
  {
    id: 'com-1',
    name: 'Combo Happy Hour (2 Caldinhos + 2 Cervejas)',
    description: 'Escolha 2 Caldinhos (500ml) + 2 Cervejas 600ml. Economia de R$ 12,00.',
    category: 'combos',
    basePrice: 58.90,
    originalPrice: 70.90,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&q=80&w=800',
    isPopular: true,
    available: true,
    rating: 0,
    reviewsCount: 0,
    prepTimeMinutes: 15,
    comboSlots: COMBO_SLOTS_HAPPY_HOUR,
  },
  {
    id: 'com-2',
    name: 'Combo Casal (2 Caldinhos + 1 Petisco Grande)',
    description: 'Escolha 2 caldinhos à vontade + 1 petisco grande. Serve duas pessoas.',
    category: 'combos',
    basePrice: 69.90,
    originalPrice: 82.90,
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=800',
    available: true,
    rating: 0,
    reviewsCount: 0,
    prepTimeMinutes: 22,
    comboSlots: COMBO_SLOTS_CASAL,
  },
  {
    id: 'com-3',
    name: 'Combo Família (3 Caldinhos + Petisco + 2 Bebidas)',
    description: 'Escolha 3 caldinhos à vontade + 1 petisco grande + 2 cervejas 600ml. Serve de quatro a cinco pessoas.',
    category: 'combos',
    basePrice: 96.90,
    originalPrice: 119.90,
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&q=80&w=800',
    isPopular: true,
    available: true,
    rating: 0,
    reviewsCount: 0,
    prepTimeMinutes: 28,
    comboSlots: COMBO_SLOTS_FAMILIA,
  },
];

